
spring:
  application:
    name: social-media-auth
  data:
    mongodb:
      uri: db_connection_url

server:
  port: 8090
  servlet:
    context-path: /social-media/auth/api

social-media:
  api:
    host: http://localhost:8080/social-media/api

app:
  config:
    keypair:
      algorithmType: RSA
      keySize: 2048