
spring:
  application:
    name: social-media-auth
  data:
    mongodb:
      uri: mongodb+srv://markfieldsuk:z4iFMp8cPFXw5hvC@cluster0.rsy1hrv.mongodb.net/social-media-demo

server:
  port: 8090
  servlet:
    context-path: /social-media/auth/api

social-media:
  api:
    host: http://localhost:8080/social-media/api

app:
  config:
    keypair:
      algorithmType: RSA
      keySize: 2048